### ISSUE TITLE
Add 'role change' teaming test case

### ISSUE THREAD

**Issue by harshita-sharma011** [mayadata-io/oep#151]
ProjectOwner and ProjectAdmin can change member role.

**Comment by prabhatkumarthakur** [comment]
@harshita-sharma011  Only project Owner can change the member role

**Comment by prabhatkumarthakur** [comment]
can you please verify this issue and close it.

**Comment by harshita-sharma011** [comment]
This PR closes this issue: https://github.com/mayadata-io/oep-e2e-gcp/pull/29
